apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  kubernetes-backend.json:
    '{
      "spring.kafka.bootstrap-servers": "kafka-0.kafka-headless.default.svc.cluster.local:9092",
      "logging.level.com.vibration.backend": "DEBUG"
     }'