apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1.0.0
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
        version: v1.0.0
    spec:
      containers:
        - name: backend
          image: registry.gitlab.com/mdastfm/backend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: kubernetes-backend.json
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
              scheme: HTTPS
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
              scheme: HTTPS
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3