apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend-server
    version: v1.0.0
  ports:
    - protocol: TCP
      port: 8090