kind: Service
apiVersion: v1
metadata:
  name: react-service
spec:
  type: LoadBalancer
  selector:
    app: react
    version: v1.0.0
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 3000
      # Port to forward to inside the pod
      targetPort: 3000
      nodePort: 31000
