apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-v1.0.0
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
        version: v1.0.0
    spec:
      containers:
        - name: react
          image: registry.gitlab.com/mdastfm/front-end-development:master
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: react-config
                  key: REACT_APP_BACKEND_URL
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3